version: '3'

services:
  mediawiki:
      build: .
      restart: always
      ports:
        - 8080:80
      links:
        - database
      volumes:
        - images:/var/www/html/images
        #- ./LocalSettings.php:/var/www/html/LocalSettings.php
        - ./ldapprovider.json:/etc/mediawiki/ldapprovider.json
  database:
      image: mariadb
      restart: always
      volumes:
          - database:/var/lib/mysql
      environment:
        MYSQL_DATABASE: mediawiki
        MYSQL_USER: mediawiki
        MYSQL_PASSWORD: password123
        MYSQL_RANDOM_ROOT_PASSWORD: 'yes'

volumes:
  database:
  images:
